
export const ListOfValue = [{
    id: 1,
    value: 'Aggresive',
    display: 'Aggresive'
  }, {
    id: 2,
    value: 'Careless',
    display: 'Careless'
  }, {
    id: 3,
    value: 'Caring',
    display: 'Caring'
  }, {
    id: 4,
    value: 'Clever',
    display: 'Clever'
  }, {
    id: 5,
    value: 'Cold',
    display: 'Cold'
  }, {
    id: 6,
    value: 'Competitive',
    display: 'Competitive'
  },{
    id: 7,
    value: 'Deceptive',
    display: 'Deceptive'
  },{
    id: 8,
    value: 'Demanding',
    display: 'Demanding'
  }, {
    id: 9,
    value: 'Friendly',
    display: 'Friendly'
  }, {
    id: 10,
    value: 'Generous',
    display: 'Generous'
  }, {
    id: 11,
    value: 'Greedy',
    display: 'Greedy'
  }, {
    id: 12,
    value: 'Humorous',
    display: 'Humorous'
  }, {
    id: 13,
    value: 'Mellow',
    display: 'Mellow'
  },{
    id: 14,
    value: 'Messy',
    display: 'Messy'
  },{
    id: 15,
    value: 'Narcissistic',
    display: 'Narcissistic'
  }, {
    id: 16,
    value: 'Patient',
    display: 'Patient'
  }, {
    id: 17,
    value: 'Quiet',
    display: 'Quiet'
  }, {
    id: 18,
    value: 'Sensitive',
    display: 'Sensitive'
  }, {
    id: 19,
    value: 'Shy',
    display: 'Shy'
  }, {
    id: 20,
    value: 'Stubborn',
    display: 'Stubborn'
  }]